FROM python:3.9-slim

WORKDIR /app

COPY services/python/setup.py ./
COPY services/python/stocktrade_insights ./stocktrade_insights
COPY services/fastapi/main.py ./

RUN pip install fastapi uvicorn pydantic requests

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
